site_name: test
plugins:
    - markdownwavedrom

nav:
    - 'README.md'
    - 'test.md'

extra_javascript:
    # use local.
    # - wavedrom.unpkg.js
    # - skin-default.js
    # from internet.
    - https://cdn.jsdelivr.net/npm/wavedrom@2.1.2/wavedrom.unpkg.js
    - https://wavedrom.com/skins/default.js

